name: action-da-paixao
on:
  push:
    branches:
      - main

jobs:
  run_workflow:
    name: Main Branch Validation
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Publish Summary
        shell: bash {0}
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          echo "### Eduarda Reichow & Gabriel :two_hearts: :two_hearts:" >> $GITHUB_STEP_SUMMARY
